### ISSUE TITLE
Typo in repo name

### ISSUE THREAD

**Issue by djbpitt** [jeh253/Revelations-and-Psalms#1]
Oops! The repo name includes “Pslams” in place of “Psalms” (likewise in the README.md file). The repo owner can fix the name from the Settings tab. GitHub should be able to manage the renaming behind the scenes, so local clones created before the change should continue to work. The team may want to take care of this during their first meeting.

**Comment by jeh253** [comment]
I've corrected the repository name as well as the readme file. Thank you for bringing this to our attention!

**Comment by djbpitt** [comment]
@jeh253 Quick work! The spelling is fixed now in the README.md file, but …

… the repo name, as rendered at the top of the page, still reads “pslams”. To fix this, too: If you click on the “Settings” tab (only the repo owner can do this) you should see a box and a button that lets you rename the repo itself, to match the way the README.md file now reports the name. You should be able to make that change by typing the new name in the box and clicking the “Rename” button. Adjusting GitHub configurations can be confusing at first, so feel free to bring this up at your project meeting, where your project mentor can help, or ask any of the instructors during office hours.

**Comment by jeh253** [comment]
Ah, I see what happened. I thought the repo name change saved automatically, and didn't click the rename button afterwards. I'll keep the issue open in case anyone wants to talk about it at the meeting, but I've corrected it.
